spring.application.name: discovery-server
#spring.cloud.config.uri: http://localhost:8888/
#spring.config.import: configserver:http://localhost:8888/

#for docker container
spring.cloud.config.uri: http://config-server:8888/
spring.config.import: configserver:http://config-server:8888/
spring:
  config:
    discovery:
      enabled: true
      service-id: config-server